### ISSUE TITLE
Version warning

### ISSUE THREAD

**Issue by PhilPJL** [cake-contrib/Cake.Prompt#11]
HI,

getting this warning:
![image](https://user-images.githubusercontent.com/271656/159924388-eba2dd56-ae96-4477-9798-26350a6e85f4.png)

add-in loaded with

#addin nuget:?package=Cake.FileHelpers&version=4.0.1&loaddependencies=true
#addin nuget:?package=Cake.Email&version=1.0.2&loaddependencies=true
#addin nuget:?package=Cake.Prompt&version=1.0.15&loaddependencies=true

**Comment by PhilPJL** [comment]
@gep13 I guess I could.  It's a small project,

**Comment by megakid** [comment]
Hi there. I am still partially active - I will take a look at this later. I
forked this as the previous incarnation was dead and I wanted to bring this
in as an cake project.

I’m not sure off the top of my head how I will publish this now it’s part
of the cake org.

Cheers

**Comment by megakid** [comment]
Sorry I missed this - No objections what so ever to adding a new maintainer!

**Comment by PhilPJL** [comment]
I guess I took too long - see you've fixed this :)
